name:                advent-of-code-y2020
version:             0.1.0.0
github:              "githubuser/advent-of-code-y2020"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/advent-of-code-y2020#readme>

dependencies:
- base >= 4.7 && < 5
- split >= 0.2 && < 0.3
- array >= 0.5 && < 0.6
- containers >= 0.6 && < 0.7
- regex-tdfa >= 1.3 && < 1.4
- unordered-containers >= 0.2.11 && < 0.3
- regex-applicative >= 0.3 && < 0.4
- mtl >= 2.2 && < 2.3
- vector >= 0.12 && < 0.13
- hashable >= 1.3 && < 1.4
- text >= 1.2 && < 1.3
- Earley >= 0.13 && < 0.14

library:
  source-dirs: src

executables:
  advent-of-code-y2020-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-y2020

tests:
  advent-of-code-y2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-y2020
